Added Makefiles.

diff --git a/DiscreteSurf/Makefile b/DiscreteSurf/Makefile
--- a/DiscreteSurf/Makefile
+++ b/DiscreteSurf/Makefile
@@ -1,38 +1,56 @@
-# Makefile for DiscSurf
+#      ******************************************************************
+#      *                                                                *
+#      * File:          Makefile                                        *
+#      * Authors: Ney Secco and John Jasa                               *
+#      * Based on Gaetan Kenway's Makefiles                             *
+#      * Starting date: 07-27-2016                                      *
+#      * Last modified: 07-27-2016                                      *
+#      *                                                                *
+#      ******************************************************************
 
-# Specify calling options
-.PHONY: clean help
-
-# Specify config and rules file
-CONFIG_FILE = config.mk
-RULES_FILE = common.mk
-
-# Folder with source file where we should run make
-SRC_DIR = src/modules \
-          src/ADT \
-          src/CGNSinterface
-
-# Important directories
-MOD_DIR = $(CURDIR)/mod
-OBJ_DIR = $(CURDIR)/obj
-
-# Add config and rules file
-include ${CONFIG_FILE}
-include ${RULES_FILE}
+SUBDIR_SRC    = src/common \
+		src/CGNSInterface \
+		src/ADT
 
 default:
-# Run make in each subdirectory
-	@for subdir in $(SRC_DIR) ; \
+# Check if the config.mk file is in the config dir.
+	@if [ ! -f "config/config.mk" ]; then \
+	echo "Before compiling, copy an existing config file from the "; \
+	echo "config/defaults/ directory to the config/ directory and  "; \
+	echo "rename to config.mk. For example:"; \
+	echo " ";\
+	echo "  cp config/defaults/config.LINUX_INTEL_OPENMPI.mk config/config.mk"; \
+	echo " ";\
+	echo "The modify this config file as required. Typically the CGNS directory "; \
+	echo "will have to be modified. With the config file specified, rerun "; \
+	echo "'make' and the build will start"; \
+	else make discretesurf;\
+	fi;
+
+clean:
+	@echo " Making clean ... "
+
+	@for subdir in $(SUBDIR_SRC) ; \
 		do \
 			echo; \
 			echo "making $@ in $$subdir"; \
 			echo; \
-			export MOD_DIR; \
-			export OBJ_DIR; \
-			export CONFIG_FILE; \
-			export RULES_FILE; \
-			$(MAKE) all -C $$subdir; \
-			(cd $$subdir && mv *.o $(OBJ_DIR)/.); \
-			(cd $$subdir && mv *.mod $(MOD_DIR)/.); \
+			(cd $$subdir && make $@) || exit 1; \
 		done
+	rm -f *~ config.mk;
+	rm -f lib/lib* mod/* obj/*
+
+discretesurf:
+	mkdir -p obj
+	mkdir -p mod
+	ln -sf config/config.mk config.mk
+	@for subdir in $(SUBDIR_SRC) ; \
+		do \
+			echo "making $@ in $$subdir"; \
+			echo; \
+			(cd $$subdir && make) || exit 1; \
+		done
+	(cd lib && make)
+	(cd src/python/f2py && make)
+
 
